$Env:URL="postgresql://admin:1234@postgres18:5432/bank_app_core"
$Env:USER="admin"
$Env:DB="bank_app_core"
$Env:PASSWORD="1234"
$Env:URLFORTEST="postgresql://admin:1234@localhost:5433/bank_app_core"
Write-Host "Zmienne Srodowiskowe Ustawione!"
