"""fix account id to in transactions

Revision ID: 6cbd3ffa06ee
Revises: 3314d183d24c
Create Date: 2026-02-23 20:31:04.336597

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6cbd3ffa06ee'
down_revision: Union[str, Sequence[str], None] = '3314d183d24c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactions', 'account_id_from',
               existing_type=sa.VARCHAR(length=12),
               type_=sa.String(length=36),
               existing_nullable=False)
    op.alter_column('transactions', 'account_id_to',
               existing_type=sa.VARCHAR(length=12),
               type_=sa.String(length=36),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactions', 'account_id_to',
               existing_type=sa.String(length=36),
               type_=sa.VARCHAR(length=12),
               existing_nullable=False)
    op.alter_column('transactions', 'account_id_from',
               existing_type=sa.String(length=36),
               type_=sa.VARCHAR(length=12),
               existing_nullable=False)
    # ### end Alembic commands ###
