"""added account_id to operation_history.py

Revision ID: 291bd84524ed
Revises: 32569bac8bc7
Create Date: 2026-03-25 00:31:28.785087

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '291bd84524ed'
down_revision: Union[str, Sequence[str], None] = '32569bac8bc7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('operation_history', sa.Column('account_id', sa.String(length=36), nullable=True))
    op.create_foreign_key(None, 'operation_history', 'accounts', ['account_id'], ['account_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'operation_history', type_='foreignkey')
    op.drop_column('operation_history', 'account_id')
    # ### end Alembic commands ###
