"""add operation_history tables

Revision ID: b9f16247867f
Revises: 412cfa2d9043
Create Date: 2026-03-24 23:49:49.286251

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9f16247867f'
down_revision: Union[str, Sequence[str], None] = '412cfa2d9043'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('operation_history',
    sa.Column('operation_id', sa.UUID(), nullable=False),
    sa.Column('account_from_id', sa.String(length=36), nullable=False),
    sa.Column('account_to_id', sa.String(length=36), nullable=False),
    sa.Column('operation_type', sa.String(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_from_id'], ['accounts.account_id'], ),
    sa.ForeignKeyConstraint(['account_to_id'], ['accounts.account_id'], ),
    sa.PrimaryKeyConstraint('operation_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('operation_history')
    # ### end Alembic commands ###
