"""fix account_to_id and account_to_out to nullable true

Revision ID: c960ed77b470
Revises: b9f16247867f
Create Date: 2026-03-25 00:00:47.624853

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c960ed77b470'
down_revision: Union[str, Sequence[str], None] = 'b9f16247867f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('operation_history', 'account_from_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.alter_column('operation_history', 'account_to_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('operation_history', 'account_to_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.alter_column('operation_history', 'account_from_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    # ### end Alembic commands ###
