"""Fix accounts transactions

Revision ID: a8b7559b7890
Revises: 38bd310fc74d
Create Date: 2026-02-23 18:37:11.406606

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8b7559b7890'
down_revision: Union[str, Sequence[str], None] = '38bd310fc74d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('accounts_user_id_fkey'), 'accounts', type_='foreignkey')
    op.create_foreign_key(None, 'accounts', 'users', ['user_id'], ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'accounts', type_='foreignkey')
    op.create_foreign_key(op.f('accounts_user_id_fkey'), 'accounts', 'users', ['user_id'], ['user_id'], ondelete='RESTRICT')
    # ### end Alembic commands ###
